/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE DATABASE IF NOT EXISTS `mytest`;

DROP TABLE IF EXISTS `tbl_classes`;

DROP TABLE IF EXISTS `tbl_student`;

CREATE TABLE `tbl_student` (
  `sn` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `classId` BIGINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `age` INT NULL,
  `score` DOUBLE NULL,
  `birthday` DATETIME NULL)
 ENGINE=InnoDB;

CREATE INDEX `classId_i`
  ON `tbl_student` (`classId`);

INSERT `tbl_student` VALUES (null, 1, '张三', 14, 88, now()),
  (null, 1, '李四', 15, 99, now()),
  (null, 1, '王五', 14, 77, now()),
  (null, 2, '赵六', 16, 66, now()),
  (null, 2, '孙七', 14, 75, now());

CREATE TABLE `tbl_classes` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `name_i`
  ON `tbl_classes` (`name`);

INSERT `tbl_classes` VALUES (1, '⼀年级⼀班'), (2, '⼀年级⼆班');